version: "3"

networks:
  pgd-network:
    external: false

volumes:
  pgd-volume:
    driver: local

services:
  mysql:
    image: mariadb:10.3.23
    container_name: mariadb
    tty: true
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - pgd-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "80:80"
    depends_on:
      - mysql
    links:
      - mysql:mariadb
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - pgd-network